[package]
name = "xtask"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
# xtask-common = { git = "https://github.com/tracel-ai/xtask", tag = "v1.0.0" }
# xtask-macros = { git = "https://github.com/tracel-ai/xtask", tag = "v1.0.0" }
xtask-common = { git = "https://github.com/tracel-ai/xtask" }
xtask-macros = { git = "https://github.com/tracel-ai/xtask" }

[dev-dependencies]
rstest = { workspace = true }
