on:
  workflow_call:
    inputs:
        runner-os:
          type: string
          description: The Linux distribution to use on the Linux runner
          required: true
        rust-toolchain:
          type: string
          description: Rust toolchain to install
          required: true
        cache-key:
          type: string
          description: The cache name as defined in the CI workflow matrix
          required: true

jobs:
  linux-std:
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      # --------------------------------------------------------------------------------
      - name: setup
        uses: ./.github/actions/setup-rust
        with:
          rust-toolchain: ${{ inputs.rust-toolchain }}
          cache-key: ${{ inputs.cache-key }}
      # --------------------------------------------------------------------------------
      - name: Setup Linux runner
        uses: ./.github/actions/setup-linux
      # --------------------------------------------------------------------------------
      - name: Install grcov
        run: cargo xtask coverage install
      # --------------------------------------------------------------------------------
      - name: Crates Build
        run: cargo xtask --enable-coverage ci --target crates build
      # --------------------------------------------------------------------------------
      - name: Crates Unit Tests
        run: cargo xtask --enable-coverage ci --target crates unit-tests
      # --------------------------------------------------------------------------------
      - name: Crates Integration Tests
        run: cargo xtask --enable-coverage ci --target crates integration-tests
      # --------------------------------------------------------------------------------
      - name: Examples Unit Tests
        run: cargo xtask ci --target examples unit-tests
      # --------------------------------------------------------------------------------
      - name: Examples Integration Tests
        run: cargo xtask ci --target examples integration-tests
      # --------------------------------------------------------------------------------
      - name: Generate lcov.info
        # /* is to exclude std library code coverage from analysis
        run: cargo xtask coverage generate --ignore "/*,xtask/*,examples/*"
      # --------------------------------------------------------------------------------
      - name: Codecov upload lcov.info
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

