on:
  workflow_call:
    inputs:
      runner-os:
        type: string
        description: The Linux distribution to use on the Linux runner
        required: true
      rust-toolchain:
        type: string
        description: Rust toolchain to install
        required: true
      cache-key:
        type: string
        description: The cache name as defined in the CI workflow matrix
        required: true

jobs:
  linux-no-std:
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      # --------------------------------------------------------------------------------
      - name: setup
        uses: ./.github/actions/setup-rust
        with:
          rust-toolchain: ${{ inputs.rust-toolchain }}
          cache-key: ${{ inputs.cache-key }}
      # --------------------------------------------------------------------------------
      - name: Setup Linux runner
        uses: ./.github/actions/setup-linux
      # --------------------------------------------------------------------------------
      - name: Crates Build
        run: cargo xtask --execution-environment no-std ci build
      # --------------------------------------------------------------------------------
      - name: Crates Unit Tests
        run: cargo xtask --execution-environment no-std ci unit-tests
